zuul:
  routes:
    search:
      path: /products/_search
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://elasticsearch:9200
    products:
      path: /products/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://rvstore-product-api:9001/products
    orders:
      path: /orders/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://rvstore-order-api:9002/orders
    auth:
      path: /auth/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://rvstore-auth-api:9003/auth