version: '3.8'
services:
  ui:
    image: public.ecr.aws/vergeops/rvstore-ui
    restart: always
    ports:
     - "80:80"
  rvstore-api-gateway:
    image: public.ecr.aws/vergeops/rvstore-gateway-service
    restart: always
    ports:
     - "9000:9000"
    environment:
     - SPRING_PROFILES_ACTIVE=compose
  rvstore-auth-api:
    image: public.ecr.aws/vergeops/rvstore-auth-api
    restart: always
    ports:
     - "9003:9003"
  rvstore-product-api:
    image: public.ecr.aws/vergeops/rvstore-product-api
    restart: always
    ports:
     - "9001:9001"
    environment:
     - ENVIRONMENT=containerized
  rvstore-order-api:
    image: public.ecr.aws/vergeops/rvstore-order-api
    restart: always
    ports:
     - "9002:9002"
    environment:
     - SPRING_PROFILES_ACTIVE=compose
  rvstore-orders-mongodb:
    image: "mongo"
    restart: always
    ports:
     - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
     - MONGO_INITDB_ROOT_PASSWORD=secret
  rvstore-order-simulator:
    image: public.ecr.aws/vergeops/rvstore-order-simulator
    environment:
     - SPRING_PROFILES_ACTIVE=compose
  rvstore-product-sync:
    image: public.ecr.aws/vergeops/rvstore-product-sync
  elasticsearch:
    image: public.ecr.aws/vergeops/rvstore-elasticsearch:latest
    ports:
      - "9200:9200"
    environment:
     - discovery.type=single-node
     - ES_JAVA_OPTS=-Xms256m -Xmx256m
     - http.cors.allow-origin=*
     - http.cors.enabled=true
     - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
     - http.cors.allow-credentials=true