apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx
    ver: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      ver: v2
  template:
    metadata:
      labels:
        app: nginx
        ver: v2
    spec:
      containers:
      - name: nginx
        image: vergeops/versioned-nginx:2.0
