apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnd
  labels:
    app: dnd
    ver: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnd
      ver: v1
  template:
    metadata:
      labels:
        app: dnd
        ver: v1
    spec:
      containers:
        - name: my-main-container
          image: alpine
          env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
        - name: dind
          image: docker:18.05-dind
          securityContext:
            privileged: true
          volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
      volumes:
      - name: dind-storage
        emptyDir: {}
