apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.services.elasticsearch.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  serviceName: {{ .Values.services.elasticsearch.serviceName }}
  selector:
    matchLabels:
      app: {{ .Values.services.elasticsearch.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.elasticsearch.label }}
    spec:
      containers:
      - name: elasticsearch
        image: {{ .Values.services.elasticsearch.image }}
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: http.cors.allow-origin
          value: "*"
        - name: http.cors.enabled
          value: "true"
        - name: http.cors.allow-headers
          value: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        - name: http.cors.allow-credentials
          value: "true"
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.elasticsearch.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.services.elasticsearch.label }}
  ports:
  - protocol: TCP
    port: {{ .Values.services.elasticsearch.port }}