apiVersion: v1
kind: LimitRange
metadata:
  name: advk8slimitrange
  namespace: advk8s
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      min:
        cpu: 250m
        memory: 128Mi
      max:
        cpu: 1500m
        memory: 1.5Gi
      type: Container