version: '3'
services:
  wordpress:
    image: "wordpress:latest"
    restart: always
    ports:
     - "80:80"
    environment:
     - WORDPRESS_DB_HOST=mysql
     - WORDPRESS_DB_USER=exampleuser
     - WORDPRESS_DB_PASSWORD=examplepass
     - WORDPRESS_DB_NAME=exampledb
  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
     - "3306:3306"
    environment:
     - MYSQL_DATABASE=exampledb
     - MYSQL_USER=exampleuser
     - MYSQL_PASSWORD=examplepass
     - MYSQL_RANDOM_ROOT_PASSWORD='1'