apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: advk8s
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: advk8s
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort
