apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: advk8s
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: mydb
  namespace: advk8s
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9377
