apiVersion: v1
kind: Pod
metadata:
  name: small-pod-1
  namespace: advk8s
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        cpu: "1000m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "256Mi"